Database display added; includes important updates to databaseController
CS-3733-D23-Team-E/Prototype-Two pull request #8
Opened 2023-04-05 01:23 UTC by michibatoryu

2023-04-05 04:19 UTC, Kreeevin requested changes
Importing from a CSV file causes the following error
![image](https://user-images.githubusercontent.com/67293695/229979877-78400682-a68b-4c1c-bc03-50049b466b4a.png)

Getting "No Content In Table" message for all tables but "move".

Delete row functionality does not seem to work if more than just the Node ID text box is filled

Add functionality also doesn't seem to work consistently; Getting an "Improper formatting" error.

Entering the Database screen takes a long time, and sometimes causes the program to not respond or crash.

Database Menu button does not highlight on hover, which is different than the rest of the buttons

2023-04-05 04:19 UTC, KalticCodes commented on src/main/java/Database/DatabaseController.java
> -    return c;
manual made constructor vs lombok; irrelevant stylistic choice

2023-04-05 04:19 UTC, KalticCodes commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +    // ObservableList locationList = FXCollections.observableArrayList(locationArrList);
why is this code commented? if it was just for testing please remove it (applies to all commented code)

2023-04-05 04:19 UTC, KalticCodes commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +  private void switchActiveTable(String db) {
why not use the enum here?

2023-04-05 04:19 UTC, KalticCodes commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +  private void addRow(DatabaseController dC, Popup windowPop) {
why does this need to take in a DatabaseController here?

2023-04-05 04:19 UTC, KalticCodes commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +    switch (databaseChoice.getValue()) {
why does databaseChoice not use the enum?

2023-04-05 04:23 UTC, michibatoryu commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +  private void addRow(DatabaseController dC, Popup windowPop) {
a scope thing; dC isn't declared globally for the class (same for the Popup)

2023-04-05 04:29 UTC, michibatoryu commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +    // ObservableList locationList = FXCollections.observableArrayList(locationArrList);
yeah those were for testing - removed them

2023-04-05 04:30 UTC, Kreeevin commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +    // ObservableList locationList = FXCollections.observableArrayList(locationArrList);
Sounds good; resolving

2023-04-05 04:34 UTC, michibatoryu commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +    switch (databaseChoice.getValue()) {
true, will change that

2023-04-05 04:51 UTC, Kreeevin commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +  private void addRow(DatabaseController dC, Popup windowPop) {
why note just use DatabaseController.INSTANCE?

2023-04-05 04:53 UTC, michibatoryu commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +  private void addRow(DatabaseController dC, Popup windowPop) {
ooooooh I forgot that that was a thing that worked now I'll do that

2023-04-05 17:31 UTC, Kreeevin requested changes
Couple different issues associated with importing from CSV

![image](https://user-images.githubusercontent.com/67293695/230157583-941aba7d-9e80-4661-b75d-2072af73d7d1.png)
![image](https://user-images.githubusercontent.com/67293695/230157760-979a5c30-215a-4071-9360-a5bee07c5913.png)

Database display page is off center compared to the rest of the application; opening the page from the default window size results in the page being basically blank, with the database selection combobox being half cut off. Maybe add some indication that the user needs to increase the size of the screen?

2023-04-05 17:31 UTC, KalticCodes commented on src/main/java/Database/DatabaseController.java
> +import static edu.wpi.teame.map.LocationName.NodeType.stringToNodeType;
if you import teame.map.Floor, you should automatically get the enum and the methods associate with it. Same thing for teame.map.LocationName.NodeType

2023-04-05 17:31 UTC, KalticCodes commented on src/main/java/Database/DatabaseController.java
> +  }*/
Commented out code

2023-04-05 17:31 UTC, KalticCodes commented on src/main/java/Database/DatabaseController.java
>    public List<HospitalEdge> getEdges() {
not a now thing, but could be worth looking into a List<Object> getFromTable(Table table) method for the future

2023-04-05 17:31 UTC, KalticCodes commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +    choices.add(DatabaseController.Table.EDGE);
For the future, I think there may be an easy way to do Enum->ObservableArray? not completely sure

2023-04-05 17:31 UTC, KalticCodes commented on src/main/java/edu/wpi/teame/controllers/DatabaseViewController.java
> +    switch (databaseChoice.getValue()) {
Confirmed, resolving

2023-04-05 17:31 UTC, Kreeevin commented on src/main/java/Database/DatabaseController.java
> +                rs.getString("longName") + "",
+ "" not needed here, getString should already return a string

2023-04-06 03:03 UTC, Kreeevin requested changes
Just a few small issues, all behavior confirmed

2023-04-06 03:03 UTC, Kreeevin commented on src/main/java/Database/DatabaseController.java
> +  public static void main(String[] args) {
do we need this main method here? if it's just for testing make it a test case or remove it

2023-04-06 03:03 UTC, Kreeevin commented on src/main/java/Database/DatabaseController.java
> +    // System.out.println("Opened database successfully");
Why comment this status report?

2023-04-06 03:07 UTC, Kreeevin approved these changes
All behavior confirmed, all code reviewed. Approving

2023-04-06 03:08 UTC, merged